name: check_deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get number of commits in the difference
        run: |
          git branch -a
          COUNT = `git rev-list origin/production..origin/master --count`
          echo '::set-output name=DIFF_COUNT::$COUNT'
        id: difference-count
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo count = ${{ steps.difference-count.outputs.DIFF_COUNT }}
          echo ${{ expr steps.difference-count.outputs.DIFF_COUNT > 10 }}
          echo ${{ steps.difference-count.outputs.DIFF_COUNT < 100 }}
          echo test, and deploy your project.
      - name: if test
        if: steps.difference-count.outputs.DIFF_COUNT > 10
        run: echo 10 over
      - name: if test2
        if: steps.difference-count.outputs.DIFF_COUNT < 100
        run: echo 100 under
