name: check_deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get number of commits in the difference
        run: |
          git branch -a 
          git rev-list origin/production..origin/master --count
          git rev-list origin/production..origin/master
          echo test
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
