name: check_deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get number of commits in the difference
        run: |
          git branch -a
          COUNT=`git rev-list origin/production..origin/master --count`
          echo ::set-output name=DIFF_COUNT::`git rev-list origin/production..origin/master --count`
        id: difference-count
      - name: Slack Notification
        if: steps.difference-count.outputs.DIFF_COUNT > 50
        run: echo 50 over
