name: check_deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: checkout production
        uses: actions/checkout@v2
        with:
          ref: production
      - name: get number of commits in the difference
        run: |
          git branch -a 
          git rev-list origin/production..origin/master --count
          echo test
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
