name: check_deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get number of commits in the difference
        run: git rev-list origin/production..origin/master --count  
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
